In [84]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler,OneHotEncoder
from sklearn.model_selection import train_test_split
import seaborn as sb
sb.set_style("white")
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import GradientBoostingClassifier
from xgboost import XGBClassifier
from catboost import CatBoostClassifier
from lightgbm import LGBMClassifier
from sklearn.neural_network import MLPClassifier
import time

import warnings
warnings.filterwarnings('ignore')

In [63]:
import tensorflow as tf
from tensorflow.keras.models import Sequential,Model
from tensorflow.keras.layers import Dense,Input,Dropout
from tensorflow.keras.utils import to_categorical,plot_model

In [2]:
data = pd.read_csv("C:/Users/hp/Downloads/Studies/Data Mining/cp3/latest.csv")
data

,match_id,season,start_date,venue,innings,ball,batting_team,bowling_team,striker,non_striker,...,extras,wides,noballs,byes,legbyes,penalty,wicket_type,player_dismissed,other_wicket_type,other_player_dismissed
0,1384424,2023/24,2023-11-02,"Wankhede Stadium, Mumbai",1,0.1,India,Sri Lanka,RG Sharma,Shubman Gill,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1384424,2023/24,2023-11-02,"Wankhede Stadium, Mumbai",1,0.2,India,Sri Lanka,RG Sharma,Shubman Gill,...,0,NaN,NaN,NaN,NaN,NaN,bowled,RG Sharma,NaN,NaN
2,1384424,2023/24,2023-11-02,"Wankhede Stadium, Mumbai",1,0.3,India,Sri Lanka,V Kohli,Shubman Gill,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1384424,2023/24,2023-11-02,"Wankhede Stadium, Mumbai",1,0.4,India,Sri Lanka,V Kohli,Shubman Gill,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1384424,2023/24,2023-11-02,"Wankhede Stadium, Mumbai",1,0.5,India,Sri Lanka,V Kohli,Shubman Gill,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22574,32,2023/24,2023-11-01,"Maharashtra Cricket Association Stadium, Pune",2,34.5,New Zealand,South Africa,MJ Henry,GD Phillips,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22575,32,2023/24,2023-11-01,"Maharashtra Cricket Association Stadium, Pune",2,34.6,New Zealand,South Africa,MJ Henry,GD Phillips,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22576,32,2023/24,2023-11-01,"Maharashtra Cricket Association Stadium, Pune",2,35.1,New Zealand,South Africa,GD Phillips,MJ Henry,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22577,32,2023/24,2023-11-01,"Maharashtra Cricket Association Stadium, Pune",2,35.2,New Zealand,South Africa,GD Phillips,MJ Henry,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22578,32,2023/24,2023-11-01,"Maharashtra Cricket Association Stadium, Pune",2,35.3,New Zealand,South Africa,GD Phillips,MJ Henry,...,0,NaN,NaN,NaN,NaN,NaN,caught,GD Phillips,NaN,NaN

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22579 entries, 0 to 22578
Data columns (total 22 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   match_id                22579 non-null  int64
 1   season                  22579 non-null  object
 2   start_date              22579 non-null  object
 3   venue                   22579 non-null  object
 4   innings                 22579 non-null  int64
 5   ball                    22579 non-null  float64
 6   batting_team            22579 non-null  object
 7   bowling_team            22579 non-null  object
 8   striker                 22579 non-null  object
 9   non_striker             22579 non-null  object
 10  bowler                  22579 non-null  object
 11  runs_off_bat            22579 non-null  int64
 12  extras                  22579 non-null  int64
 13  wides                   580 non-null    float64
 14  noballs                 50 non-null     float64
 15  byes                    32 non-null     float64
 16  legbyes                 165 non-null    float64
 17  penalty                 1 non-null      float64
 18  wicket_type             641 non-null    object
 19  player_dismissed        641 non-null    object
 20  other_wicket_type       1 non-null      object
 21  other_player_dismissed  1 non-null      object
dtypes: float64(6), int64(4), object(12)
memory usage: 3.8+ MB

In [4]:
for i in data.columns:
    if len(data[i].unique()):
        print(data[i].value_counts())
        print()
        print()

27         618
19         616
22         614
8          613
23         601
1384433    601
21         599
1384427    598
18         597
1384430    597
7          597
4          594
26         589
6          585
30         582
11         575
28         566
10         561
1384429    558
17         558
2          557
5          557
13         556
1384431    545
15         539
1          525
9          525
32         524
16         519
29         518
1384425    489
14         485
1384428    485
31         473
1384426    470
20         448
24         445
12         442
3          441
1384424    431
1384432    425
25         361
Name: match_id, dtype: int64


2023/24    22579
Name: season, dtype: int64


2023-10-10    1210
2023-10-28    1184
2023-11-04    1068
2023-10-21    1064
2023-10-07    1035
2023-10-23     614
2023-11-10     601
2023-10-24     601
2023-10-22     599
2023-11-07     597
2023-10-20     597
2023-10-27     589
2023-10-09     585
2023-10-30     582
2023-10-13     575
2023-10-12     561
2023-11-06     558
2023-10-19     558
2023-10-08     557
2023-10-06     557
2023-10-15     556
2023-11-08     545
2023-10-17     539
2023-10-11     525
2023-10-05     525
2023-11-01     524
2023-10-18     519
2023-10-29     518
2023-11-03     489
2023-10-16     485
2023-11-05     485
2023-10-31     473
2023-10-25     445
2023-10-14     442
2023-11-02     431
2023-11-09     425
2023-10-26     361
Name: start_date, dtype: int64


MA Chidambaram Stadium, Chepauk, Chennai                                 2854
Himachal Pradesh Cricket Association Stadium, Dharamsala                 2794
Arun Jaitley Stadium, Delhi                                              2678
Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium, Lucknow    2669
Maharashtra Cricket Association Stadium, Pune                            2209
Narendra Modi Stadium, Ahmedabad                                         2166
Wankhede Stadium, Mumbai                                                 2077
M Chinnaswamy Stadium, Bengaluru                                         1853
Rajiv Gandhi International Stadium, Uppal, Hyderabad                     1755
Eden Gardens, Kolkata                                                    1524
Name: venue, dtype: int64


1    12549
2    10030
Name: innings, dtype: int64


0.1     85
9.1     85
1.1     85
17.1    85
12.3    84
        ..
32.8     1
1.9      1
41.9     1
41.8     1
29.8     1
Name: ball, Length: 398, dtype: int64


South Africa    2559
Afghanistan     2459
New Zealand     2391
Sri Lanka       2322
Australia       2289
Bangladesh      2206
India           2131
Pakistan        2106
Netherlands     2089
England         2027
Name: batting_team, dtype: int64


Afghanistan     2465
New Zealand     2449
South Africa    2383
Sri Lanka       2343
Netherlands     2253
Pakistan        2249
Australia       2169
Bangladesh      2163
England         2121
India           1984
Name: bowling_team, dtype: int64


V Kohli               633
Q de Kock             555
R Ravindra            537
Ibrahim Zadran        510
HE van der Dussen     507
                     ...
Tanzim Hasan Sakib      6
JR Hazlewood            5
MADI Hemantha           4
Usama Mir               3
AT Carey                2
Name: striker, Length: 144, dtype: int64


R Ravindra           637
V Kohli              626
HE van der Dussen    540
Q de Kock            535
Ibrahim Zadran       470
                    ...
Mohammad Wasim         6
Shariz Ahmad           4
TG Southee             4
Usama Mir              3
CBRLS Kumara           1
Name: non_striker, Length: 142, dtype: int64


Rashid Khan              531
TA Boult                 503
MJ Santner               501
Mujeeb Ur Rahman         500
D Madushanka             496
                        ...
DJ Mitchell                9
KIC Asalanka               6
Rahmat Shah                6
Nazmul Hossain Shanto      6
V Kohli                    3
Name: bowler, Length: 98, dtype: int64


0    12025
1     7078
4     1936
2      940
6      537
3       61
5        2
Name: runs_off_bat, dtype: int64


0    21751
1      751
4       25
5       25
2       21
3        6
Name: extras, dtype: int64


1.0    540
5.0     24
2.0     12
3.0      4
Name: wides, dtype: int64


1.0    50
Name: noballs, dtype: int64


1.0    17
4.0    13
2.0     1
3.0     1
Name: byes, dtype: int64


1.0    144
4.0     12
2.0      8
3.0      1
Name: legbyes, dtype: int64


5.0    1
Name: penalty, dtype: int64


caught               393
bowled               122
lbw                   68
run out               33
caught and bowled     13
stumped               11
retired hurt           1
Name: wicket_type, dtype: int64


Rahmanullah Gurbaz    9
Q de Kock             9
BKG Mendis            9
RG Sharma             8
JE Root               8
                     ..
R Klein               1
M Pathirana           1
Noor Ahmad            1
MADI Hemantha         1
TA Boult              1
Name: player_dismissed, Length: 138, dtype: int64


timed out    1
Name: other_wicket_type, dtype: int64


AD Mathews    1
Name: other_player_dismissed, dtype: int64

In [5]:
print(data.isnull().sum())

match_id                      0
season                        0
start_date                    0
venue                         0
innings                       0
ball                          0
batting_team                  0
bowling_team                  0
striker                       0
non_striker                   0
bowler                        0
runs_off_bat                  0
extras                        0
wides                     21999
noballs                   22529
byes                      22547
legbyes                   22414
penalty                   22578
wicket_type               21938
player_dismissed          21938
other_wicket_type         22578
other_player_dismissed    22578
dtype: int64

### Data Pre-processing and Feature Engineering

In [6]:
#creating a column 'wicket' with value 1 if a wicket has fallen in that ball
data["wicket"] = data.apply(lambda row: 1 if isinstance(row["player_dismissed"], str) 
                            or isinstance(row["other_player_dismissed"], str) else 0, axis=1)

In [7]:
#dropping 'Other Wicket Type' and 'Other Player Dismissed' since they are not required
data.drop(['other_wicket_type','other_player_dismissed'], axis = 1, inplace = True)

In [8]:
#Filling None values in runs-related attributes
data[["wides", "noballs", "byes", "legbyes", "penalty"]] = data[["wides", "noballs", "byes", "legbyes", "penalty"]].fillna(0)

In [9]:
#Filling None values in wickets-related attributes
data.wicket_type.fillna("no wicket", inplace=True)
data.player_dismissed.fillna("no wicket", inplace=True)

In [10]:
#Separating over number and ball number
data["ball"] = data["ball"].astype(str)
data[["over", "ball_num"]] = data["ball"].str.split(".", expand=True).astype(int)
data["ball"] = data["ball"].astype(float)
data["over"] = data["over"] + 1
data["ball_left"] = 306 - (data["over"]*6 + data["ball_num"])
data["ball_left"] = data["ball_left"].clip(lower=0)

In [11]:
#creating a new column to add total runs scored per ball
data["total_runs"] = data["runs_off_bat"] + data["extras"]

In [12]:
#creating a new column to keep track of total runs scored so far in the innings
data["score"] = data.groupby(["match_id", "innings"])["total_runs"].cumsum()

In [13]:
#creating a new column to keep track of wickets remaining
data["wickets_remaining"] = data.groupby(["match_id","innings"])["wicket"].apply(lambda x: 10 - x.cumsum())

In [14]:
#calculating current run rate
data["run_rate"] = data.groupby(["match_id","innings"]).apply(lambda x: (x["score"]*6)/(300-x["ball_left"])).reset_index(level=[0,1], drop=True)

In [15]:
#setting targets in the data
targets = data[data["innings"] == 1].groupby("match_id")["score"].max().reset_index()
targets.rename(columns={"score": "target"}, inplace=True)

data = data.merge(targets, on="match_id", how="left")
data.loc[data['innings'] == 1, 'target'] = 0
data.loc[data['innings'] == 2, 'target'] += 1

In [16]:
#Finding the winning team
idx_winner = data.loc[data.groupby('match_id')['score'].idxmax()]
winners = idx_winner.set_index('match_id')['batting_team']
data['winner'] = data['match_id'].map(winners)

In [17]:
data

,match_id,season,start_date,venue,innings,ball,batting_team,bowling_team,striker,non_striker,...,wicket,over,ball_num,ball_left,total_runs,score,wickets_remaining,run_rate,target,winner
0,1384424,2023/24,2023-11-02,"Wankhede Stadium, Mumbai",1,0.1,India,Sri Lanka,RG Sharma,Shubman Gill,...,0,1,1,299,4,4,10,24.000000,0,India
1,1384424,2023/24,2023-11-02,"Wankhede Stadium, Mumbai",1,0.2,India,Sri Lanka,RG Sharma,Shubman Gill,...,1,1,2,298,0,4,9,12.000000,0,India
2,1384424,2023/24,2023-11-02,"Wankhede Stadium, Mumbai",1,0.3,India,Sri Lanka,V Kohli,Shubman Gill,...,0,1,3,297,0,4,9,8.000000,0,India
3,1384424,2023/24,2023-11-02,"Wankhede Stadium, Mumbai",1,0.4,India,Sri Lanka,V Kohli,Shubman Gill,...,0,1,4,296,0,4,9,6.000000,0,India
4,1384424,2023/24,2023-11-02,"Wankhede Stadium, Mumbai",1,0.5,India,Sri Lanka,V Kohli,Shubman Gill,...,0,1,5,295,0,4,9,4.800000,0,India
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22574,32,2023/24,2023-11-01,"Maharashtra Cricket Association Stadium, Pune",2,34.5,New Zealand,South Africa,MJ Henry,GD Phillips,...,0,35,5,91,0,161,1,4.622010,358,South Africa
22575,32,2023/24,2023-11-01,"Maharashtra Cricket Association Stadium, Pune",2,34.6,New Zealand,South Africa,MJ Henry,GD Phillips,...,0,35,6,90,0,161,1,4.600000,358,South Africa
22576,32,2023/24,2023-11-01,"Maharashtra Cricket Association Stadium, Pune",2,35.1,New Zealand,South Africa,GD Phillips,MJ Henry,...,0,36,1,89,0,161,1,4.578199,358,South Africa
22577,32,2023/24,2023-11-01,"Maharashtra Cricket Association Stadium, Pune",2,35.2,New Zealand,South Africa,GD Phillips,MJ Henry,...,0,36,2,88,6,167,1,4.726415,358,South Africa
22578,32,2023/24,2023-11-01,"Maharashtra Cricket Association Stadium, Pune",2,35.3,New Zealand,South Africa,GD Phillips,MJ Henry,...,1,36,3,87,0,167,0,4.704225,358,South Africa

In [18]:
#Setting Req runs and req run rate for second innings
mask = data['target'] > 0

data.loc[mask, 'req_runs'] = data.loc[mask, 'target'] - data.loc[mask, 'score']
data.loc[mask, 'req_rr'] = (data.loc[mask, 'req_runs'] * 6) / data.loc[mask, 'ball_left']

In [20]:
data.fillna(0, inplace=True)

In [21]:
#Creating Target Variable named 'result' which shows 1 if the batting team won, 0 otherwise
data["result"] = data.apply(lambda x: 1 if x["batting_team"] == x["winner"] else 0, axis=1)

In [22]:
data.head()

,match_id,season,start_date,venue,innings,ball,batting_team,bowling_team,striker,non_striker,...,ball_left,total_runs,score,wickets_remaining,run_rate,target,winner,req_runs,req_rr,result
0,1384424,2023/24,2023-11-02,"Wankhede Stadium, Mumbai",1,0.1,India,Sri Lanka,RG Sharma,Shubman Gill,...,299,4,4,10,24.0,0,India,0.0,0.0,1
1,1384424,2023/24,2023-11-02,"Wankhede Stadium, Mumbai",1,0.2,India,Sri Lanka,RG Sharma,Shubman Gill,...,298,0,4,9,12.0,0,India,0.0,0.0,1
2,1384424,2023/24,2023-11-02,"Wankhede Stadium, Mumbai",1,0.3,India,Sri Lanka,V Kohli,Shubman Gill,...,297,0,4,9,8.0,0,India,0.0,0.0,1
3,1384424,2023/24,2023-11-02,"Wankhede Stadium, Mumbai",1,0.4,India,Sri Lanka,V Kohli,Shubman Gill,...,296,0,4,9,6.0,0,India,0.0,0.0,1
4,1384424,2023/24,2023-11-02,"Wankhede Stadium, Mumbai",1,0.5,India,Sri Lanka,V Kohli,Shubman Gill,...,295,0,4,9,4.8,0,India,0.0,0.0,1

### Model to predict Winner of the match

In [23]:
data.columns

Index(['match_id', 'season', 'start_date', 'venue', 'innings', 'ball',
       'batting_team', 'bowling_team', 'striker', 'non_striker', 'bowler',
       'runs_off_bat', 'extras', 'wides', 'noballs', 'byes', 'legbyes',
       'penalty', 'wicket_type', 'player_dismissed', 'wicket', 'over',
       'ball_num', 'ball_left', 'total_runs', 'score', 'wickets_remaining',
       'run_rate', 'target', 'winner', 'req_runs', 'req_rr', 'result'],
      dtype='object')

In [28]:
#filtering required columns for modelling
df_model = data[["venue", "batting_team", "bowling_team", "ball", "score", "run_rate", "req_rr",
                      "ball_left", "req_runs",'wickets_remaining', "target", "result"]]

In [29]:
#shuffling the dataset
df_model = df_model.sample(frac=1)

In [30]:
df_model = df_model[~(df_model.req_rr > 100)]

In [31]:
X = df_model.iloc[:,:-1]
y = df_model.iloc[:, -1]

In [38]:
ohe_cols = ['venue', 'batting_team', 'bowling_team']
scale_cols = ['score', 'target','ball', 'run_rate', 'req_rr', 'ball_left', 'req_runs','wickets_remaining']

In [34]:
#Hyperparameter Tuning for
#   1. Logitistic Regression
#   2. Gradient Boosting
#   3. XGBoost
#   4. CatBoost
#   5. LightGBM Classifier
#   6. Deep Learning: MLP

param_grids = {
    'LogisticRegression': {
        'classifier__C': [0.1, 1, 10, 100],
        'classifier__penalty': ['l1', 'l2']
    },
    'GradientBoosting': {
        'classifier__learning_rate': [1e-5, 1e-3, 3e-1, 3e-5, 5e-1, 5e-5],
        'classifier__n_estimators': [50, 100, 200, 300],
        'classifier__max_depth': [3, 5, 7]
    },
    'XGBoost': {
        'classifier__learning_rate': [1e-5, 1e-3, 3e-1, 3e-5, 5e-1, 5e-5],
        'classifier__n_estimators': [50, 100, 200, 300],
        'classifier__max_depth': [3, 5, 7]
    },
    'CatBoost': {
        'classifier__learning_rate': [1e-5, 1e-3, 3e-1, 3e-5, 5e-1, 5e-5],
        'classifier__n_estimators': [50, 100, 200, 300],
        'classifier__depth': [3, 5, 7]
    },
    'LGBMClassifier': {
        'classifier__learning_rate': [1e-5, 1e-3, 3e-1, 3e-5, 5e-1, 5e-5],
        'classifier__n_estimators': [50, 100, 200, 300],
        'classifier__max_depth': [3, 5, 7]
    },
    'DNN': {
        'classifier__learning_rate_init': [1e-5, 1e-3, 3e-1, 3e-5, 5e-1, 5e-5],
        'classifier__batch_size': [8, 16, 32, 64],
        'classifier__alpha': [0.1, 0.01, 0.001]
    }
}

In [39]:
#Building the Pipeline

ct = ColumnTransformer(transformers=[('cat', OneHotEncoder(sparse=False, drop="first"), ohe_cols),
        ('num', StandardScaler(), scale_cols)])

pipelines = {
    'LogisticRegression': Pipeline([('transformer', ct), ('classifier', LogisticRegression())]),
    'GradientBoosting': Pipeline([('transformer', ct), ('classifier', GradientBoostingClassifier())]),
    'XGBoost': Pipeline([('transformer', ct), ('classifier', XGBClassifier())]),
    'CatBoost': Pipeline([('transformer', ct), ('classifier', CatBoostClassifier())]),
    'LGBMClassifier': Pipeline([('transformer', ct), ('classifier', LGBMClassifier())]),
    'DNN': Pipeline([('transformer', ct), ('classifier', MLPClassifier(max_iter=100))]),

}

In [40]:
#Running the models
start_time = time.time()

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=83)

for model_name, pipeline in pipelines.items():
    print(f"Performing grid search for {model_name}")
    grid_search = GridSearchCV(pipeline, param_grids[model_name], cv=5, scoring='accuracy', n_jobs=-1)
    grid_search.fit(X_train, y_train)

    print(f"Best parameters found for {model_name}: {grid_search.best_params_}")
    print(f"Best cross-validation accuracy for {model_name}: {grid_search.best_score_:.4f}")

    test_accuracy = grid_search.score(X_test, y_test)
    print(f"Test set accuracy for {model_name}: {test_accuracy:.4f}\n")
    
    print("--- %s seconds ---" % (time.time() - start_time))
    print()
    print()
    start_time = time.time()

Performing grid search for LogisticRegression
Best parameters found for LogisticRegression: {'classifier__C': 100, 'classifier__penalty': 'l2'}
Best cross-validation accuracy for LogisticRegression: 0.9301
Test set accuracy for LogisticRegression: 0.9322

--- 4.3592143058776855 seconds ---


Performing grid search for GradientBoosting
Best parameters found for GradientBoosting: {'classifier__learning_rate': 0.3, 'classifier__max_depth': 3, 'classifier__n_estimators': 100}
Best cross-validation accuracy for GradientBoosting: 1.0000
Test set accuracy for GradientBoosting: 1.0000

--- 1145.0884323120117 seconds ---


Performing grid search for XGBoost
Best parameters found for XGBoost: {'classifier__learning_rate': 0.3, 'classifier__max_depth': 3, 'classifier__n_estimators': 100}
Best cross-validation accuracy for XGBoost: 1.0000
Test set accuracy for XGBoost: 1.0000

--- 62.598756551742554 seconds ---


Performing grid search for CatBoost
0:	learn: 0.5565997	total: 156ms	remaining: 7.65s
1:	learn: 0.4560492	total: 169ms	remaining: 4.06s
2:	learn: 0.3793275	total: 182ms	remaining: 2.85s
3:	learn: 0.3459146	total: 193ms	remaining: 2.22s
4:	learn: 0.2833504	total: 202ms	remaining: 1.81s
5:	learn: 0.2611717	total: 211ms	remaining: 1.54s
6:	learn: 0.2269433	total: 221ms	remaining: 1.36s
7:	learn: 0.1957649	total: 229ms	remaining: 1.2s
8:	learn: 0.1757062	total: 236ms	remaining: 1.07s
9:	learn: 0.1543784	total: 242ms	remaining: 969ms
10:	learn: 0.1384024	total: 249ms	remaining: 883ms
11:	learn: 0.1280810	total: 256ms	remaining: 810ms
12:	learn: 0.1128893	total: 263ms	remaining: 750ms
13:	learn: 0.1077580	total: 271ms	remaining: 696ms
14:	learn: 0.0932243	total: 278ms	remaining: 648ms
15:	learn: 0.0820449	total: 285ms	remaining: 605ms
16:	learn: 0.0712899	total: 292ms	remaining: 567ms
17:	learn: 0.0639145	total: 299ms	remaining: 531ms
18:	learn: 0.0588002	total: 306ms	remaining: 499ms
19:	learn: 0.0516107	total: 313ms	remaining: 469ms
20:	learn: 0.0449415	total: 319ms	remaining: 441ms
21:	learn: 0.0413684	total: 326ms	remaining: 415ms
22:	learn: 0.0369444	total: 333ms	remaining: 391ms
23:	learn: 0.0337908	total: 340ms	remaining: 368ms
24:	learn: 0.0276005	total: 346ms	remaining: 346ms
25:	learn: 0.0251038	total: 353ms	remaining: 326ms
26:	learn: 0.0226018	total: 361ms	remaining: 308ms
27:	learn: 0.0216396	total: 369ms	remaining: 290ms
28:	learn: 0.0203019	total: 377ms	remaining: 273ms
29:	learn: 0.0197170	total: 386ms	remaining: 257ms
30:	learn: 0.0181846	total: 395ms	remaining: 242ms
31:	learn: 0.0174400	total: 403ms	remaining: 227ms
32:	learn: 0.0165519	total: 412ms	remaining: 212ms
33:	learn: 0.0158507	total: 421ms	remaining: 198ms
34:	learn: 0.0147228	total: 428ms	remaining: 184ms
35:	learn: 0.0134745	total: 436ms	remaining: 170ms
36:	learn: 0.0121071	total: 444ms	remaining: 156ms
37:	learn: 0.0104910	total: 451ms	remaining: 142ms
38:	learn: 0.0092073	total: 459ms	remaining: 129ms
39:	learn: 0.0084940	total: 467ms	remaining: 117ms
40:	learn: 0.0075789	total: 475ms	remaining: 104ms
41:	learn: 0.0070735	total: 483ms	remaining: 91.9ms
42:	learn: 0.0067479	total: 490ms	remaining: 79.8ms
43:	learn: 0.0063433	total: 498ms	remaining: 68ms
44:	learn: 0.0056033	total: 506ms	remaining: 56.2ms
45:	learn: 0.0052101	total: 514ms	remaining: 44.7ms
46:	learn: 0.0049342	total: 522ms	remaining: 33.3ms
47:	learn: 0.0045532	total: 529ms	remaining: 22.1ms
48:	learn: 0.0042493	total: 536ms	remaining: 10.9ms
49:	learn: 0.0038995	total: 542ms	remaining: 0us
Best parameters found for CatBoost: {'classifier__depth': 3, 'classifier__learning_rate': 0.3, 'classifier__n_estimators': 50}
Best cross-validation accuracy for CatBoost: 1.0000
Test set accuracy for CatBoost: 1.0000

--- 488.51829385757446 seconds ---


Performing grid search for LGBMClassifier
[LightGBM] [Info] Number of positive: 8672, number of negative: 8260
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.001193 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 1630
[LightGBM] [Info] Number of data points in the train set: 16932, number of used features: 35
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.512166 -> initscore=0.048675
[LightGBM] [Info] Start training from score 0.048675
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
Best parameters found for LGBMClassifier: {'classifier__learning_rate': 0.3, 'classifier__max_depth': 3, 'classifier__n_estimators': 100}
Best cross-validation accuracy for LGBMClassifier: 1.0000
Test set accuracy for LGBMClassifier: 1.0000

--- 78.76473927497864 seconds ---


Performing grid search for DNN
Best parameters found for DNN: {'classifier__alpha': 0.01, 'classifier__batch_size': 64, 'classifier__learning_rate_init': 5e-05}
Best cross-validation accuracy for DNN: 1.0000
Test set accuracy for DNN: 1.0000

--- 2400.5249106884003 seconds ---

### Final Prediction using Categorical Boost

In [82]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=83)

ct = ColumnTransformer(transformers=[('cat', OneHotEncoder(sparse=False, drop="first"), ohe_cols),
        ('num', StandardScaler(), scale_cols)])

pipe = Pipeline([('transformer', ct),
    ('CatBoost', CatBoostClassifier(depth=3, learning_rate=0.3, n_estimators=50))])

In [83]:
pipe.fit(X_train, y_train)
pred = pipe.predict(X_test)
acc = accuracy_score(y_test, pred)
acc

0:	learn: 0.5565997	total: 8.35ms	remaining: 409ms
1:	learn: 0.4560492	total: 16.5ms	remaining: 397ms
2:	learn: 0.3793275	total: 24.5ms	remaining: 383ms
3:	learn: 0.3459146	total: 32.2ms	remaining: 371ms
4:	learn: 0.2833504	total: 41ms	remaining: 369ms
5:	learn: 0.2611717	total: 49.4ms	remaining: 362ms
6:	learn: 0.2269433	total: 58ms	remaining: 356ms
7:	learn: 0.1957649	total: 65.7ms	remaining: 345ms
8:	learn: 0.1757062	total: 74ms	remaining: 337ms
9:	learn: 0.1543784	total: 82.1ms	remaining: 328ms
10:	learn: 0.1384024	total: 89.9ms	remaining: 319ms
11:	learn: 0.1280810	total: 97.4ms	remaining: 308ms
12:	learn: 0.1128893	total: 106ms	remaining: 301ms
13:	learn: 0.1077580	total: 113ms	remaining: 292ms
14:	learn: 0.0932243	total: 121ms	remaining: 283ms
15:	learn: 0.0820449	total: 129ms	remaining: 274ms
16:	learn: 0.0712899	total: 137ms	remaining: 266ms
17:	learn: 0.0639145	total: 145ms	remaining: 257ms
18:	learn: 0.0588002	total: 152ms	remaining: 248ms
19:	learn: 0.0516107	total: 160ms	remaining: 240ms
20:	learn: 0.0449415	total: 168ms	remaining: 231ms
21:	learn: 0.0413684	total: 175ms	remaining: 223ms
22:	learn: 0.0369444	total: 183ms	remaining: 215ms
23:	learn: 0.0337908	total: 191ms	remaining: 207ms
24:	learn: 0.0276005	total: 198ms	remaining: 198ms
25:	learn: 0.0251038	total: 207ms	remaining: 191ms
26:	learn: 0.0226018	total: 216ms	remaining: 184ms
27:	learn: 0.0216396	total: 224ms	remaining: 176ms
28:	learn: 0.0203019	total: 231ms	remaining: 167ms
29:	learn: 0.0197170	total: 236ms	remaining: 158ms
30:	learn: 0.0181846	total: 242ms	remaining: 148ms
31:	learn: 0.0174400	total: 248ms	remaining: 139ms
32:	learn: 0.0165519	total: 255ms	remaining: 131ms
33:	learn: 0.0158507	total: 262ms	remaining: 123ms
34:	learn: 0.0147228	total: 270ms	remaining: 116ms
35:	learn: 0.0134745	total: 277ms	remaining: 108ms
36:	learn: 0.0121071	total: 285ms	remaining: 100ms
37:	learn: 0.0104910	total: 293ms	remaining: 92.6ms
38:	learn: 0.0092073	total: 301ms	remaining: 85ms
39:	learn: 0.0084940	total: 309ms	remaining: 77.2ms
40:	learn: 0.0075789	total: 317ms	remaining: 69.5ms
41:	learn: 0.0070735	total: 324ms	remaining: 61.8ms
42:	learn: 0.0067479	total: 332ms	remaining: 54ms
43:	learn: 0.0063433	total: 339ms	remaining: 46.3ms
44:	learn: 0.0056033	total: 347ms	remaining: 38.6ms
45:	learn: 0.0052101	total: 355ms	remaining: 30.8ms
46:	learn: 0.0049342	total: 362ms	remaining: 23.1ms
47:	learn: 0.0045532	total: 369ms	remaining: 15.4ms
48:	learn: 0.0042493	total: 377ms	remaining: 7.69ms
49:	learn: 0.0038995	total: 383ms	remaining: 0us

1.0

In [85]:
report = classification_report(y_test, pred)
print(report)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      2751
           1       1.00      1.00      1.00      2894

    accuracy                           1.00      5645
   macro avg       1.00      1.00      1.00      5645
weighted avg       1.00      1.00      1.00      5645

### Calculating Run Rate for all the teams

In [92]:
idx_rr = data.groupby(['match_id', 'innings'])['ball'].idxmax()
cols = ['batting_team', 'score','run_rate','ball_left']
run_rate_df = data.loc[idx_rr, cols]
run_rate_df

      batting_team  score  run_rate  ball_left
5502       England    282  5.640000          0
5723   New Zealand    283  7.788991         82
6025      Pakistan    286  5.836735          6
6280   Netherlands    205  4.979757         53
6508   Afghanistan    156  4.178571         76
...            ...    ...       ...        ...
4000   Netherlands    179  4.794643         76
2755     Sri Lanka    171  3.664286         20
2897   New Zealand    172  7.371429        160
4907   Afghanistan    244  4.880000          0
5198  South Africa    247  5.200000         15

[84 rows x 4 columns]

In [94]:
run_rate_df['balls_played'] = 300-run_rate_df['ball_left']

team_avg_rr = pd.DataFrame()
team_avg_rr['total_runs'] = (run_rate_df.groupby(["batting_team"])["score"].sum())
team_avg_rr['total_balls_played'] = (run_rate_df.groupby(["batting_team"])["balls_played"].sum())
team_avg_rr

              total_runs  total_balls_played
batting_team
Afghanistan         2095                2386
Australia           2324                2228
Bangladesh          1747                2150
England             1908                1973
India               2113                2078
Netherlands         1612                2012
New Zealand         2537                2328
Pakistan            2084                2044
South Africa        2685                2489
Sri Lanka           2048                2267

In [95]:
team_avg_rr['run_rate']= (team_avg_rr['total_runs']*6)/team_avg_rr['total_balls_played']
team_avg_rr

              total_runs  total_balls_played  run_rate
batting_team
Afghanistan         2095                2386  5.268231
Australia           2324                2228  6.258528
Bangladesh          1747                2150  4.875349
England             1908                1973  5.802331
India               2113                2078  6.101059
Netherlands         1612                2012  4.807157
New Zealand         2537                2328  6.538660
Pakistan            2084                2044  6.117417
South Africa        2685                2489  6.472479
Sri Lanka           2048                2267  5.420379

### Creating new DataFrame for SemiFinals Winners Prediction

In [87]:
X_test.columns

Index(['venue', 'batting_team', 'bowling_team', 'ball', 'score', 'run_rate',
       'req_rr', 'ball_left', 'req_runs', 'wickets_remaining', 'target'],
      dtype='object')

In [96]:
new_data = pd.DataFrame(np.array(["Wankhede Stadium, Mumbai","India",'New Zealand',0.1,0,6.101059,0,299,0,10,0]).reshape(1,-1))
new_data.columns = X_test.columns

new_data2 = pd.DataFrame({'venue': ["Wankhede Stadium, Mumbai","Eden Gardens, Kolkata","Eden Gardens, Kolkata"],
            'batting_team': ["New Zealand","South Africa", "Australia"], 'bowling_team': ['India', 'Australia','South Africa'],
            'ball': [0.1,0.1,0.1], 'score':[0,0,0], 'run_rate':[6.538660,6.472479,6.258528], 'req_rr':[0,0,0],
            'ball_left':[299,299,299], 'req_runs':[0,0,0], 'wickets_remaining':[10,10,10], 'target':[0,0,0]
           })

new_data = pd.concat([new_data, new_data2], ignore_index=True)
new_data

,venue,batting_team,bowling_team,ball,score,run_rate,req_rr,ball_left,req_runs,wickets_remaining,target
0,"Wankhede Stadium, Mumbai",India,New Zealand,0.1,0,6.101059,0,299,0,10,0
1,"Wankhede Stadium, Mumbai",New Zealand,India,0.1,0,6.53866,0,299,0,10,0
2,"Eden Gardens, Kolkata",South Africa,Australia,0.1,0,6.472479,0,299,0,10,0
3,"Eden Gardens, Kolkata",Australia,South Africa,0.1,0,6.258528,0,299,0,10,0

In [97]:
pred2 = pipe.predict(new_data)
pred2

array([1, 0, 1, 1], dtype=int64)

In [98]:
prob = pipe.predict_proba(new_data)
np.round(prob, 3)

array([[0.009, 0.991],
       [0.802, 0.198],
       [0.001, 0.999],
       [0.039, 0.961]])

According to our model India will win the first semi-finals and enter the finals. However, both South Africa and Australia show high probability of winning if given the chance to bat first. If South Africa gets to bat first, then it's chances of winning are 99%.

### Finals Winner Prediction

In [99]:
finals = pd.DataFrame({'venue': ["Narendra Modi Stadium, Ahmedabad","Narendra Modi Stadium, Ahmedabad","Narendra Modi Stadium, Ahmedabad","Narendra Modi Stadium, Ahmedabad"],
            'batting_team': ["India","India","South Africa", "Australia"], 'bowling_team': ['Australia','South Africa','India','India'],
            'ball': [0.1,0.1,0.1,0.1], 'score':[0,0,0,0], 'run_rate':[6.101059,6.101059,6.472479,6.258528], 'req_rr':[0,0,0,0],
            'ball_left':[299,299,299,299], 'req_runs':[0,0,0,0], 'wickets_remaining':[10,10,10,10], 'target':[0,0,0,0]
           })
finals.columns = X_test.columns

pred_finals = pipe.predict(finals)
pred_finals

array([1, 1, 1, 0], dtype=int64)

In [100]:
prob = pipe.predict_proba(finals)
np.round(prob, 3)

array([[0.042, 0.958],
       [0.169, 0.831],
       [0.426, 0.574],
       [0.98 , 0.02 ]])

If India plays the finals against Australia, India has 95% chance of winning if Australia bowls first. If India bowls first, then India has 98% chance of winning.

If India and South Africa play the finals, then India has 83% chance of winning if South Africa bowls first. Whereas, if India bowls, they have only 42% of winning the finals and ICC World Cup trophy.